import React from "react";
import axios from "axios";

const Twitter = () => {
  const TOKEN =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjaHJpc3RpYW5AY3cudml0YWxjYXJkLmNvbSIsImV4cCI6MTYzNzk1MDYwOSwiaXNzIjoidml0YWxjYXJkIiwiYXVkIjoidml0YWxjYXJkIn0.wqpzHmMN6RYycUZ3Qm42IQfuCAu2ddnj_6v3PVOV_aU";
  const HEADERS = {
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
    },
  };

  const login = () => {
    axios
      .get(
        "https://servicesdev.vitalcard.com:8138/Social/Twitter/RequestToken",
        HEADERS
      )
      .then((response) => {
        console.log(response);
        openWindow(response);
      });
  };

  const openWindow = (response) => {
    const oauthToken = response.data.data.OAuthToken;
    const twitterWindow = window.open(
      `https://api.twitter.com/oauth/authorize?oauth_token=${oauthToken}`
    );
    console.log(twitterWindow.location.href);
    let interval = setInterval(function () {
      if (twitterWindow.closed !== false) {
        window.clearInterval(interval);
        console.log("response " + response.data.data.OAuthToken);
      }
    }, 1000);
  };

  // TOKENS GENERATED BY TWITTER
  const oauthToken = "5_YNdQAAAAABUdu4AAABfV0KE0Y";
  const oauthVerifier = "DcVYqRNwDFfj4K2oUNK1RXZJ5kwhWfXm";

  const getAccessToken = (oauthToken, oauthVerifier) => {
    const data = {
      OAuthToken: oauthToken,
      OAuthVerifier: oauthVerifier,
    };
    axios
      .post(
        "https://servicesdev.vitalcard.com:8138/Social/Twitter/AccessToken",
        data,
        HEADERS
      )
      .catch(function (error) {
        if (error.response) {
          // Request made and server responded
          console.log(error.response.data);
          console.log(error.response.status);
          console.log(error.response.headers);
        } else if (error.request) {
          // The request was made but no response was received
          console.log(error.request);
        } else {
          // Something happened in setting up the request that triggered an Error
          console.log("Error", error.message);
        }
      });
  };

  const verifyToken = () => {
    const data = {
      AccessToken: "1460989674-N8SaiKr8WxaiJdXviP31G1PJsl4ngZw9fAREHkm",
      AccessTokenSecret: "ExCNlEJCbPnxMJK7MIPGK1KQTgIC9a1dbYQI5Tu1SHw7y",
    };
    axios
      .post(
        "https://servicesdev.vitalcard.com:8138/Social/Twitter/Post",
        data,
        HEADERS
      )
      .catch(function (error) {
        if (error.response) {
          // Request made and server responded
          console.log(error.response.data);
          console.log(error.response.status);
          console.log(error.response.headers);
        } else if (error.request) {
          // The request was made but no response was received
          console.log(error.request);
        } else {
          // Something happened in setting up the request that triggered an Error
          console.log("Error", error.message);
        }
      });
  };

  return (
    <div>
      <button onClick={login}>Login with Twitter</button>
      <button
        type="submit"
        onClick={() => getAccessToken(oauthToken, oauthVerifier)}
      >
        Get Access/Secret Token
      </button>
      <button type="submit" onClick={() => verifyToken()}>
        Verify Post
      </button>
    </div>
  );
};

export default Twitter;
